blank_issues_enabled: true
contact_links:
  - name: ðŸ’¬ GitHub Discussions
    url: https://github.com/Elion-Kara/Parallel-Hough-Transform/discussions
    about: Ask questions or discuss ideas here
  - name: ðŸ“š Documentation
    url: https://github.com/Elion-Kara/Parallel-Hough-Transform/wiki
    about: Check the wiki for setup instructions